### ISSUE TITLE
func to the power

### ISSUE THREAD

**Issue by thewieredbro** [AverageUser125/jitcalc#1]
if you put a var in an () like (x) and give it a power like (x^2) it works fine, but if you add to that another power like (x^2)^2 it crushes,
this works with every power, i just did ^2 as an example

**Comment by AverageUser125** [comment]
Okay

**Comment by AverageUser125** [comment]
Fixed in 5359c8b6854e3f491a1d816bff92e00940253a75

**Comment by AverageUser125** [comment]
if you're curious, the problem was the I created a new power function for each instance of it instead of only creating it once.
